blueprints/Qq.py
from flask import Blueprint, render_template, request, redirect, url_for, g

# 导入数据库
from exts import db
# 导入问题模型(也可以叫做导入表)
from models import QuestionsModel, AnswerModel
# 导入表单验证
from .forms import Questions, Answers

from decorator import login_required


bp = Blueprint("Qa", __name__, url_prefix="/")


# 首页展示
@bp.route('/')
def index():
    # 访问数据库 拿数据
    questions = QuestionsModel.query.order_by(QuestionsModel.create_time.desc()).all()
    return render_template("index.html", questions=questions)


# 发送问题
@bp.route('/publish_qa', methods=['GET', 'POST'])
@login_required
def publish_qa():
    if request.method == 'GET':
        return render_template("public_question.html")
    else:
        form = Questions(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionsModel(title=title, content=content, author=g.user)
            db.session.add(question)
            db.session.commit()
            return redirect(url_for("Qa.index"))
        else:
            print(form.errors)
            return redirect(url_for("Qa.publish_qa"))


# 查看详情
@bp.route('/qa/detail/<question_id>')
def qa_detail(question_id):
    question = QuestionsModel.query.get(question_id)
    return render_template("detail.html", question=question)


# 问题回答

@bp.route("/answer/publish", methods=["POST"])
@login_required
def publish_answer():
    form = Answers(request.form)
    if form.validate():
        content = form.content.data
        question_id = form.question_id.data
        answer = AnswerModel(content=content, question_id=question_id, author_id=g.user.id)
        db.session.add(answer)
        db.session.commit()
        return redirect(url_for("Qa.qa_detail", question_id=question_id))
    else:
        print(form.errors)
        return redirect(url_for("Qa.qa_detail", question_id=request.form.get("question_id")))


# 数据库查询

@bp.route("/qa/search")
def search():
    # /qa/search?q = flask
    # /qa/search/<q>
    # post,request.form
    # 获取参数
    q = request.args.get("q")
    # 从数据库里面进行模糊查找,然后返回所有标题包含q这个标题的数据
    questions = QuestionsModel.query.filter(QuestionsModel.title.like("%" + q + "%")).all()
    # questions = QuestionsModel.query.filter(QuestionsModel.title.contains(q)).all()

    return render_template("index.html", questions=questions, q=q)

blueprints/auth.py
from flask import Blueprint, render_template, jsonify, redirect, url_for, session, g
# 导入flask-mail
from exts import mail, db
from flask_mail import Message

from flask import request
from models import EmailCaptchaModel
import string
import random
from .forms import RegisterForm, LoginForm
from models import UserModel


# 生成加密密码
from werkzeug.security import generate_password_hash, check_password_hash

bp = Blueprint("auth", __name__, url_prefix="/sunfei", template_folder="templates")


# 定义视图函数
# 登录
@bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            # 数据格式校验成功,然后去数据库进行比较
            email = form.email.data
            password = form.password.data
            #  根据email 进行一个数据库查询
            user = UserModel.query.filter_by(email=email).first()
            # 如果查询的用户不存在数据库里面 说明用户第一次登录,我们可以进行一个提示
            if not user:
                print("用户不存在")
                return redirect(url_for("auth.login"))
            if check_password_hash(user.password, password):
                # cookie:
                # cookie 中不适合存储太多的数据,只适合存储少量的数据
                # cookie 一般用来存放登录授权的东西
                # flask 中的session, 是经过加密后存储在cookie中的
                session['user_id'] = user.id
                return redirect('/')
            else:
                print("密码错误")
                return redirect(url_for("auth.login"))
        else:
            print(form.errors)
            return redirect(url_for("auth.login"))


# 退出登录
@bp.route('/logout')
def logout():
    session.clear()
    return redirect("/")


# 注册
@bp.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "GET":
        return render_template('register.html')
    else:
        # 借助一个插件 进行表单的验证 flask-wtf 基于wtforms
        form = RegisterForm(request.form)
        # validate 会自动调用RegisterForm 类面的类型检查器 和定义好的检查方法
        # form.validate() 该方法会返回一个布尔类型
        if form.validate():
            # 上面验证通过,将form表单里面的各项数据进行一个数据库的存储
            email = form.email.data
            username = form.username.data
            password = generate_password_hash(form.password.data)
            user = UserModel(email=email, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            #  注册成功之后,进行页面跳转 ==> 登录页面
            return redirect(url_for("auth.login"))  # 对应上面的login视窗函数
        else:
            print(form.errors)
            # 注册失败,刷新本页面

            return redirect(url_for("auth.register"))


# 没有指定methon请求方式,默认就是GTE请求
@bp.route('/captcha/email')
# /sunfei/captcha/email?email=12345678901@qq.com
# 发送邮箱请求 获取验证码的接口
def get_email_captcha():
    email = request.args.get('email')
    source = string.digits * 4
    captcha = ''.join(random.sample(source, 4))
    message = Message(subject="孙飞课堂验证码", recipients=[email],
                      body=f"[孙飞课堂] 验证码为{captcha}。此验证码只用于进行短信登陆.15分钟内有效")
    mail.send(message)
    # memcached / redis
    #  数据库存储
    email_captcha = EmailCaptchaModel(email=email, captcha=captcha)
    db.session.add(email_captcha)
    db.session.commit()

    # result API 风格
    # {code:200/304/404/500, msg:"", data:""}
    return jsonify({"code": 200,
                    "msg": "成功",
                    "data": None})

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {#    改成jinjia2 的 资源引入方式 #}

    <link rel="stylesheet" href="{{ url_for('static',filename = "bootstrap/bootstrap.4.6.min.css") }}">
    <link rel="stylesheet" href="{{ url_for('static',filename = "css/init.css") }}">
    {% block head %}

    {% endblock %}
    {#    <link rel="stylesheet" href="../static/bootstrap/bootstrap.4.6.min.css">#}
    {#    <link rel="stylesheet" href="../static/css/init.css">#}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">知了问答</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for("Qa.index") }}">首页 <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for("Qa.publish_qa") }}">发布问答</a>
                </li>
                <li class="nav-item ml-2">
                    <form class="form-inline my-2 my-lg-0" method="GET" action="{{ url_for('Qa.search') }}">
                        <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search"
                               name="q">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                    </form>
                </li>
            </ul>

            <ul class="navbar-nav">
                {# 如果用户已经登陆 #}
                {% if user %}
                    <li class="nav-item">
                            <img src="{{ user.avatar }}" alt="avatar" id="avatar">
                    </li>
                    <li class="nav-item">
                        <span>{{ user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">退出登录</a>
                    </li>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.register') }}">注册</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block body %}{% endblock %}
</div>

</body>

</html>

templates/detail.html
{% extends "base.html" %}


{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename = "css/detail.css") }}">

{% endblock %}

{% block title %}
    <title>{{ question.title }}</title>
{% endblock %}


{% block body %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10" style="background-color: #fff;padding: 20px;">
            <h3 class="page-title">{{ question.title }}</h3>
            <p class="question-info">
                <span>作者：{{ question.author.username }}</span>
                <span>时间：{{ question.create_time }}</span>
            </p>
            <hr>
            <p class="question-content">{{ question.content }}</p>
            <hr>
            <h4 class="comment-group-title">评论（{{ question.answers|length }}）：</h4>
            <form action="{{ url_for('Qa.publish_answer') }}" method="post">
                <div class="form-group">
                    <input type="text" placeholder="请填写评论" name="content" class="form-control">
                    <input type="hidden" name="question_id" value="{{ question.id }}">
                </div>
                <div class="form-group" style="text-align: right;">
                    <button class="btn btn-primary">评论</button>
                </div>
            </form>
            <ul class="comment-group">
                {% for answer in question.answers %}
                    <li>
                        <div class="user-info">
                            <img class="avatar" src="{{ url_for("static",filename = "images/avatar.jpg") }}" alt="">
                            <span class="username">{{ answer.author.username }}</span>
                            <span class="create-time">{{ answer.create_time }}</span>
                        </div>
                        <p class="comment-content">{{ answer.content }}！</p>
                    </li>

                {% endfor %}
            </ul>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename = 'css/index.css') }}">
{% endblock %}
{% block title %}孙飞课堂-- 首页{% endblock %}
{% block body %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10">
            <ul class="question-ul">
                {% for question in questions %}
                    <li>
                        <div class="side-question">
                            <img class="side-question-avatar"
                                 src="{{ url_for('static',filename = '/images/avatar.jpg') }}" alt="">
                        </div>
                        <div class="question-main">
                            {#   注意加个参数#}
                            <div class="question-title"><a
                                    href="{{ url_for('Qa.qa_detail',question_id = question.id) }}">{{ question.title }}</a>
                            </div>
                            <div class="question-content">{{ question.content }}</div>
                            <div class="question-detail">
                                <span class="question-author">{{ question.author.username }}</span>
                                <span class="question-time">{{ question.create_time }}</span>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}
    孙飞课堂 登录页面
{% endblock %}

{% block body %}
    <div class="row mt-4">
        <div class="col"></div>
        <div class="col">
            <form method="POST">
                <div class="form-group">
                    <label for="exampleInputEmail1">邮箱</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                           name="email">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" name="password" class="form-control" id="exampleInputPassword1">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">立即登录</button>
                </div>
            </form>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

templates/public_question.html
{% extends "base.html" %}


{% block title %} 孙飞课堂 - 发布问题 {% endblock %}

{% block body %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10">
            <h1 style="text-align: center;">发布问答</h1>
            <form method="post">
                <div class="form-group">
                    <input type="text" name="title" class="form-control" placeholder="请输入标题">
                </div>
                <div class="form-group">
                    <textarea name="content" class="form-control" rows="10" placeholder="请输入内容"></textarea>
                </div>
                <div class="form-group" style="text-align: right;">
                    <button class="btn btn-primary">发布</button>
                </div>
            </form>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

templates/register.html
{#
继承父级模板
父级模块是对每一个页面公用的部分进行的一个 抽离, 为了提高重复代码的复用性

#}
{% extends "base.html" %}

{# 标题 填充 #}
{% block title %}孙飞课堂--注册页面{% endblock %}
{# 导入js文件加载 #}
{% block head %}
<script src="../static/js/register.js"></script>
{% endblock %}
{# 主要页面内容填充 #}

{% block body %}
    <div class="row mt-4">
        <div class="col"></div>
        <div class="col">
            <form method="POST">
                <div class="form-group">
                    <label for="exampleInputEmail1">邮箱</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                           name="email">
                    <small id="emailHelp" class="form-text text-muted">我们不会把邮箱用于其他用户</small>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">验证码</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="captcha">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">用户名</label>
                    <input type="text" class="form-control" name="username">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">确认密码</label>
                    <input type="password" class="form-control" name="password_confirm">
                </div>
                <button type="submit" class="btn btn-primary btn-block">立即注册</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}